###create new comment
POST http://localhost:3000/comments HTTP/1.1
content-type:application/json

{
    "content": "I like rainbows and sprinkles"
  }

###create new user test
POST http://localhost:3000/users HTTP/1.1
content-type:application/json

{
  "firstName": "lusanda",
  "lastName": "Mavuma",
  "age": 42,
  "email": "mavuma@byui.edu",
  "password": "Potter11?",
  "profession": "student"
}

###get the existing comments
GET http://localhost:3000/comments/62d220f961b7c542cad3cb09

###ddelete comment using id
DELETE http://localhost:3000/comments/62cf94847f207dbb4c409ac4

###update/modify the comment

PUT http://localhost:3000/comments/62cf98dad8269d4c36fd27ad HTTP/1.1
content-type:application/json

{
    "content": "I don't think this belongs here, it must be updated!"
  }
###
POST http://localhost:3000/posts HTTP/1.1
content-type:application/json

{
    "title": "How to see rainbows",
    "body": "Go outside after the rain",
    "userId": "userId",
    "category": "Bakes"
  }
###get post using id
GET http://localhost:3000/posts/62d200e97c5a96edb6c840b4

###add comment to a post
POST http://localhost:3000/comments/posts/62cfbe91164c7ebdb25173ff HTTP/1.1
content-type:application/json

{
    "content": "Testing if this comments will appear in the posts"
  }
