###create new comment
POST http://localhost:3000/comments HTTP/1.1
content-type:application/json

{
    "content": "I don't think this belongs here"
  }

###create new user test
POST http://localhost:3000/users HTTP/1.1
content-type:application/json

{
  "firstName": "lusanda",
  "lastName": "Mavuma",
  "age": 42,
  "email": "mavuma@byui.edu",
  "password": "Potter11?",
  "profession": "student"
}

###get the existing comments
GET http://localhost:3000/comments/62cf823b0b713104f4fd1948

###ddelete comment using id
DELETE http://localhost:3000/comments/62cf94847f207dbb4c409ac4

###
